version: '3.9'
services:
  sillypaste:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: 'localhost'
  #     DATABASE_URL: 'postgres://postgres:BoPhoz4Oolahghoow2iengei7aum8a'
  # db:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     PASTGRES_PASSWORD: BoPhoz4Oolahghoow2iengei7aum8a
